
void main(	float4 position : POSITION,
			float3 normal   : NORMAL,
			float2 texcoord : TEXCOORD0,
			out float4 oPosition : POSITION,
			out float3 objectPos: TEXCOORD0,
			out float3 oNormal: TEXCOORD1,
			out float2 oTexcoord: TEXCOORD2,
			uniform float4x4 modelViewProj)
{
	oPosition = mul(modelViewProj, position);
	objectPos = position.xyz;
	oNormal = normal;
	oTexcoord = texcoord;
}

